// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userInfo.proto

package com.example.api.grpc.userInfo;

public interface UserStrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserStr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string str = 1;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <code>string str = 1;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();
}
