// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userInfo.proto

package com.example.api.grpc.userInfo;

public interface UserInfoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserInfoReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 id = 2;</code>
   * @return The id.
   */
  long getId();
}
