// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userInfo.proto

package com.example.api.grpc.userInfo;

public interface UserInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <code>bool success = 3;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>.UserInfoResponse.Data data = 4;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.UserInfoResponse.Data data = 4;</code>
   * @return The data.
   */
  com.example.api.grpc.userInfo.UserInfoResponse.Data getData();
  /**
   * <code>.UserInfoResponse.Data data = 4;</code>
   */
  com.example.api.grpc.userInfo.UserInfoResponse.DataOrBuilder getDataOrBuilder();
}
